### ISSUE TITLE
panic: runtime error: cgo argument has Go pointer to Go pointer

### ISSUE THREAD

**Issue by and-hom** [axet/desktop#11]
I've built example and got an error:

`./example 
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running, locked to thread]:
panic(0x5867a0, 0xc82000adc0)
	/usr/lib/go-1.6/src/runtime/panic.go:464 +0x3e6
github.com/axet/desktop/go._cgoCheckPointer0(0x54e4a0, 0xc820010470, 0x0, 0x0, 0x0, 0x537360)
	github.com/axet/desktop/go/_obj/_cgo_gotypes.go:47 +0x4d
github.com/axet/desktop/go.g_main_context_invoke(0x1ba9f90, 0xc820010470)
	/home/and-hom/.go/src/github.com/axet/desktop/go/linux_gtk.go:271 +0x138
github.com/axet/desktop/go.GtkMessageLoopInvoke(0xc820010470)
	/home/and-hom/.go/src/github.com/axet/desktop/go/linux_gtk_main.go:37 +0x31
github.com/axet/desktop/go.(*DesktopSysTrayAppIndicator).setIcon(0xc820010440, 0x7f84cda932b0, 0xc820010480)
	/home/and-hom/.go/src/github.com/axet/desktop/go/desktop_linux_systray_appindicator.go:111 +0x50
github.com/axet/desktop/go.(*DesktopSysTray).setIcon(0xc820010400, 0x7f84cda932b0, 0xc820010480)
	/home/and-hom/.go/src/github.com/axet/desktop/go/desktop_linux_systray.go:111 +0x5c
github.com/axet/desktop/go.(*DesktopSysTray).SetIcon(0xc820010400, 0x7f84cda932b0, 0xc820010480)
	/home/and-hom/.go/src/github.com/axet/desktop/go/desktop.go:142 +0x35
main.main()
	/home/and-hom/.go/src/github.com/and-hom/what-are-you-doing/example.go:50 +0x542
`

`
$ cat /etc/issue
Ubuntu 16.04 LTS \n \l
$ go version
go version go1.6.1 linux/amd64
`

**Comment by axet** [comment]
Show your example please

**Comment by and-hom** [comment]
https://github.com/axet/desktop/tree/master/go#example-sys-tray-icon

**Comment by axet** [comment]
Just checked it working fine on:

  * mac osx 11.11 / go1.4
  * windows 10 / go1.5
  * ubuntu 14.04 / go1.2

I'll see what I can do.

**Comment by axet** [comment]
It seems you can do following:

GODEBUG=cgocheck=0 go run example.go

I'll try to fix code.

**Comment by and-hom** [comment]
thank you! it works! 
i use this workaround untill golang issue will be fixed
