### ISSUE TITLE
addOpenFileListener causes ExceptionInInitializerError on OS X

### ISSUE THREAD

**Issue by adolfintel** [axet/desktop#9]
I'm trying to get my app to receive file open events, so I made a simple test program:

```
AppleHandlers.getAppleHandlers().addOpenFileListener(new AppleHandlers.OpenFileHandler() {
    @Override
        public void openFile(File file) {
            JOptionPane.showMessageDialog(rootPane, file.getAbsolutePath());
        }
});
```

This is run when the application starts (after checking that it's running on a Mac), but it throws an exception:
java.lang.ExceptionInInitializerError
 at com.dosse.AppleTest.<init>(AppleTest.java:27)
 at com.dosse.AppleTest.<init>(AppleTest.java:85)
Caused by: java.lang.IllegalArgumentException: Invalid calling convention 63
 at com.sun.jna.Native.createNativeCallback(Native Method)
 ..blah blah bunch of jna classes..
 at com.github.axet.desktop.os.mac.AppleHandlers.<clinit>(AppleHandlers.java:454)
 ... 2 more

Obviously, events are not received.
Am I doing something wrong?

**Comment by axet** [comment]
This part of library is not complete. FileHandlers It is not covered yet on Windows, Linux and not fully tested on OSX.

But in your case, it seems, you need to keep references to listener and handler.

https://github.com/axet/mircle/blob/master/mircle/src/main/java/com/google/code/mircle/OSX.java

**Comment by adolfintel** [comment]
I saw that code, but your AppleHandlers class no longer has that public constructor, so I used the getAppleHandlers method which seems to do what I need. (Should I try an older version?)
The method that crashes seems to be getAppleHandlers, regardless of when I call it.
Keeping references to these Objects doesn't change anything.

**Comment by adolfintel** [comment]
Works with your old "Apple" library.
